nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.0.5/index.js"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
